language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - mysql -e 'create database diamantedesk;'
  - if [[ "$TRAVIS_PHP_VERSION"  = "hhvm" ]]; then cat travis.php.ini >> /etc/hhvm/php.ini ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-add travis.php.ini ; fi
  - composer self-update

install:
  - composer install --prefer-source --profile --no-interaction

script: vendor/bin/phpunit --version

after_script:

before_deploy:
  - rm -rf app/cache/*
  - rm -rf app/logs/*
  - zip -q -x \*.git* -x build/ -x travis.php.ini -x .travis.yml -r build/diamantedesk-application-full-$TRAVIS_TAG.zip .
  - tar --exclude=\*.git* --exclude=build --exclude=travis.php.ini --exclude=.travis.yml -zcf build/diamantedesk-application-full-$TRAVIS_TAG.tar.gz .

deploy:
  provider: releases
  api_key:
    secure: IlKj3LFMTuTWosLR8iGrR/6PMx2XMm4S0Eu+ZTU/q/GJz9EcjVaWJpfiEw0uPIYLSnyKv6J7gt/n+r7xyQ2zZlPNrvlIQB4VP6rbPcGjEh6oSrK73s8QpCAMBiyvE4ld9oNd++564/HEPIBiQtdjxo61eRezjvV+XHl76zo9lxWRMm6TnJc2ogOCHWZlOrvyvI3Si+olZGZiTIVBA2yQvySARw0HWhL3sa+f/o4RoM3uYf+fLdt0SSqcJ8yZlqsi7wqskWdOohEaq+2OzfZ747iHXOCQdYpUKv8W3d21MesWnpbg/sCymANKu5x1hGRNqNa2sD99dutIUPTAk1JPRGVOu+lzw6PmJufOyVQKCtC8wYCXTpGmdc/nKetI3Sxt6khGe2XwcR/UL0BZ9UD8hDOPFQ9HOmSE0BgRT0+wP3inFc6JsJMREbXwiK+1dgtnWsIx9xkHJMy4fWk0G90bvtl2GhkwGtyaaQLRvmABjb3p5mb7fUTU4hlfieMwKPZUTHQ2QkdAJG7NnYTOTYeUBj7oZ9WNSyYOkLep5tExUuyo/nnNAxlMfK98LOKkvPqH6INSw/5hEL1HUPQ744vnFsSahoQNVNqCcDfo4aDcHex0T9ThegasAFLYMsOF0BX8ihtoMR4spRuoAFQspiTR+aksxheLkB+IoPzn1fLUM1w=
  file:
    - build/diamantedesk-application-full-$TRAVIS_TAG.zip
    - build/diamantedesk-application-full-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    tags: true
    php: '5.6'
