files:
  - source: /**/translations/messages.en.yml
    translation: /**/translations/messages.%two_letters_code%.yml
  - source: /**/translations/jsmessages.en.yml
    translation: /**/translations/jsmessages.%two_letters_code%.yml
