diamante_automation:
  entities: []

  conditions:
    eq:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Eq'
      frontend_label: diamante.automation.condition.eq
    neq:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Neq'
      frontend_label: diamante.automation.condition.neq
    gt:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Gt'
      frontend_label: diamante.automation.condition.gt
    gte:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Gte'
      frontend_label: diamante.automation.condition.gte
    lt:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Lt'
      frontend_label: diamante.automation.condition.lt
    lte:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Lte'
      frontend_label: diamante.automation.condition.lte
    contains:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Contains'
      frontend_label: diamante.automation.condition.contains
    not_contains:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\NotContains'
      frontend_label: diamante.automation.condition.not_contains
    created:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Created'
      frontend_label: diamante.automation.condition.created
    updated:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Updated'
      frontend_label: diamante.automation.condition.updated
    removed:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Removed'
      frontend_label: diamante.automation.condition.removed
    changed:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Changed'
      frontend_label: diamante.automation.condition.changed
    changed_from:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\ChangedFrom'
      frontend_label: diamante.automation.condition.changed_from
    changed_to:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\ChangedTo'
      frontend_label: diamante.automation.condition.changed_to
    'true':
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\True'
      frontend_label: diamante.automation.condition.true
    'false':
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\False'
      frontend_label: diamante.automation.condition.false
    is_customer:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\IsCustomer'
      frontend_label: diamante.automation.condition.customer
    is_admin:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\IsAdmin'
      frontend_label: diamante.automation.condition.admin


  actions:
    update_property:
      id: @diamante_automation.action.update_property
      frontend_label: diamante.automation.action.update_property
      data_types: ['*', '!user', '!users']
    notify_by_email:
      id: @diamante_automation.action.notify_by_email
      frontend_label: diamante.automation.action.notify_by_email
      data_types: ['*']